### ISSUE TITLE
Core Data Loader

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper-loader#2]
As a geocoding system, I want the ability to translate Shape files into ElasticSearch so they can be loaded into the database and prepared for search capabilities to locate the (x,y) data

- [x] Point data loader #3 
- [x] Line data loader #4
- [x] Download data #41 
- [x] Data extraction #42 
- [ ] Automatic loading of state data #38
- [ ] Assign score to data source upon loading #39 
- [ ] Confidence level for data source #40
